application:
  file:
    terms: 
      fundamental: Termos_DP_Ensino_Fundamental.txt
      medio: Termos_DP_Ensino_Medio.txt
    easyWords: easy_words.txt
    dictionary: simple_dic.txt
logging:
  level:
    com.tonyleiva.ufrgs: INFO
server:
  port: 9000