application:
  file:
    terms: 
      level1: Termos_DP_Ensino_Medio.txt
      level2: Termos_DP_Ensino_Fundamental.txt
    easyWords: easy_words.txt
    dictionary: simple_dic.txt
logging:
  level:
    com.tonyleiva.ufrgs: INFO
server:
  port: 8080