spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/textecc?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: username
    password: password
    driver-class-name: com.mysql.jdbc.Driver
application:
  file:
    terms:
      covid: 
        fundamental: Termos_Covid19_Ensino_Fundamental.txt
      parkinson: 
        fundamental: Termos_DP_Ensino_Fundamental.txt
        medio: Termos_DP_Ensino_Medio.txt
    easyWords: easy_words.txt
    dictionary: simple_dic.txt
logging:
  level:
    com.tonyleiva.ufrgs: INFO
server:
  port: 9000